version: "3.9"
services:
  app:
    build: .
    container_name: java_app
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
    command: ["java", "Main"]
  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"

